version: "3.8"
services:
  db_setup:
    image: alpine
    volumes:
      - sbml4j_network_db:/db
      - ./database_backups:/database_backups
    command: ["/bin/sh", "-c", "cd /db && tar xfz /database_backups/BMC-KEGG61-97.0-SBML4j_publication_base.tar.gz --strip 1"]
  db_backup:
    image: alpine
    volumes:
      - sbml4j_network_db:/db
      - ./database_backups:/database_backups
    command: ["/bin/sh", "-c", "cd /database_backups && tar cfz BMC-KEGG61-97.0-SBML4j_publication_base.tar.gz /db"]
  apoc_install:
    image: alpine
    volumes:
      - ./neo4j/plugins:/plugins
    command: ["/bin/sh", "-c", "cd /plugins && wget https://github.com/neo4j-contrib/neo4j-apoc-procedures/releases/download/4.1.0.2/apoc-4.1.0.2-all.jar"]
  sbml4j_api_doc_setup:
    image: alpine
    volumes:
      - sbml4j_api_doc_vol:/definition
      - ./api_doc:/api_doc
    command: ["/bin/sh", "-c", "mkdir -p /definition && cp /api_doc/sbml4j.yaml /definition/sbml4j.yaml"]
  sbml4j_api_doc:
    image: swaggerapi/swagger-ui
    container_name: sbml4japidoc
    volumes:
      - sbml4j_api_doc_vol:/definition
    environment:
      - SWAGGER_JSON=/definition/sbml4j.yaml
    ports:
      - "9080:8080"

  sbml4jdatabase:
    image: neo4j:4.1
    container_name: sbml4jdb
    volumes:
      - sbml4j_network_db:/var/lib/neo4j/data
      - ./neo4j/plugins:/plugins
      - ./neo4j/logs:/logs
      - ./neo4j/conf:/var/lib/neo4j/conf
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_dbms_security_auth__enabled=false
      - NEO4J_dbms_memory_pagecache_size=1G
      - NEO4J_dbms_memory_heap_initial__size=2G
      - NEO4J_dbms_memory_heap_max__size=2G
      - NEO4J_dbms_security_procedures_unrestricted=apoc.algo.dijkstraWithDefaultWeight, apoc.path.expand
      - NEO4J_dbms_security_procedures_whitelist=apoc.algo.dijkstraWithDefaultWeight, apoc.path.expand
    restart: unless-stopped
    command: ["neo4j"]
  sbml4j:
    image: thortiede/sbml4j:0.2.14
    container_name: sbml4j
    volumes:
      - ./sbml4j/logs:/logs
    environment:
      - SPRING_PROFILES_ACTIVE=test
      - SPRING_DATA_NEO4j_URI=bolt://sbml4jdb:7687
      #- SPRING_DATA_NEO4j_AUTO-INDEX=update
      - SERVER_SERVLET_CONTEXTPATH=/sbml4j
      - SERVER_PORT=8080
      - OVERVIEWNETWORK_DEFAULT_BASE-NETWORK-NAME=PeCaX-Base
      - OVERVIEWNETWORK_DEFAULT_MINSIZE=1
      - OVERVIEWNETWORK_DEFAULT_MAXSIZE=2
      - OVERVIEWNETWORK_DEFAULT_TERMINATEAT=Drugtarget
      - OVERVIEWNETWORK_DEFAULT_DIRECTION=both
      - SBML4J_GENERAL_API-DOCUMENTATION-URL=http://192.168.0.69:9080/
      - SBML4J_context_minSize=1
      - SBML4J_context_maxSize=3
      - SBML4J_context_terminateAt=
      - SBML4J_context_direction=both
      - SBML4J_OUTPUT_HIDE_MODEL_U-U-I-DS=False
      - SBML4J_NETWORK_HARD-DELETE=True
      - SBML4J_NETWORK_FORCE-DELETE-OF-PUBLIC-NETWORK=True
      - SBML4J_NETWORK_DELETE-EXISTING=True
      - SBML4J_NETWORK_DELETE-DERIVED=True
      - SBML4J_NETWORK_USE-SHARED-PATHWAY-SEARCH=False
      - SBML4J_network_public-user=sbml4j
      - SBML4J_network_show-inactive-networks=False
      - SBML4J_network_allow-inactive-duplicates=True
      - SBML4J_ANNOTATION_APPEND=True
      - SBML4J_ANNOTATION_KEGGGENESSEPARATOR=+
      - SBML4J_annotation_annotate-with-links=True
      - SBML4J_csv_matching-column-name[0]=gene name
      - SBML4J_csv_matching-column-name[1]=genename
      - SBML4J_csv_matching-column-name[2]=gene.name
      - SBML4J_csv_matching-column-name[3]=gene symbol
      - SBML4J_csv_matching-column-name[4]=genesymbol
      - SBML4J_csv_matching-column-name[5]=gene.symbol
      - SBML4J_csv_matching-column-name[6]=gene
      - SBML4J_csv_matching-column-name[7]=symbol 
      - SBML4J_externalresources_mdanderson_add-md-anderson-annotation=True
      - SBML4J_externalresources_mdanderson_genelist=ABL1, AKT1, ALK, BRAF, CDK4, CDK6, CDKN2A, EGFR, ERBB2, FGFR1, FGFR2, FLT3, IDH1, KDR, KIT, KRAS, MDM2, MET, NRAS, NTRK1, NTRK2, PDGFRA, PIK3CA, PIK3R1, PTCH1, PTEN, PTPN11, PET, ROS1, SMO
      - SBML4J_externalresources_mdanderson_baseurl=https://pct.mdanderson.org/home/
      - SBML4J_externalresources_mdanderson_section=Overview
      - SBML4J_externalresources_biologicalqualifer_default-database=KEGG
      - SBML4J_externalresources_keggdatabase_pathway-link-prefix=https://www.genome.jp/kegg-bin/show_pathway?
      - SBML4J_externalresources_keggdatabase_pathway-search-prefix=https://www.genome.jp/dbget-bin/www_bfind_sub?dbkey=pathway&keywords=
    depends_on:
      - sbml4jdatabase
      - sbml4j_api_doc
    ports:
      - "8080:8080"
    restart: on-failure

volumes:
    sbml4j_network_db:
    sbml4j_api_doc_vol:
